version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_INITDB_ARGS: "-E utf8"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
  